#!/bin/bash

PORT=
HOST=

E_OK=0
E_WARNING=1
E_CRITICAL=2
E_UNKNOWN=3


show_help() {
	echo "$0 -H HOST -p PORT"
	echo
	echo 'This plugin is just a wrapper around "check_udp" to send strings with $ to icinga'
	echo
}

# process args
while [ ! -z "$1" ]; do 
	case $1 in
		-H)	shift; HOST=$1 ;;
		-p)	shift; PORT=$1 ;;
		-h)	show_help; exit 1 ;;
	esac
	shift
done

/usr/lib64/nagios/plugins/check_udp -H $HOST -p $PORT -s "$38$01$00$00$00$00$00$00$00" -e ""
exit 0
