#!/bin/bash
/usr/lib64/nagios/plugins/check_ping -H $1 -w $2 -c $3
status=$?
if [[ $status -ne 0 && $status -ne 3 ]]; then
    # $1 validates in check_ping plugin
    mtr -rc 15 $1 | sed 's/|--//'
fi
exit $status
